[custom]
;不要随意改变关键字，否则会导致出错
;不要乱改ruleset的顺序，会影响googleplay下载，把某些cn的google域名进行了直连
;acl4SSR规则
;个人调整，2026-02-19 15:03

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=DIRECT,[]DOMAIN-SUFFIX,kyapi.xyz
ruleset=🐟 漏网之鱼,[]DOMAIN-SUFFIX,su.anywayfosec.xyz

ruleset=🛑 广告拦截,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list

ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
ruleset=🤖 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=🤖 AI,https://raw.githubusercontent.com/WestLi/MC_Detect/master/Grok_X.list
ruleset=🤖 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.list
ruleset=🤖 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.list
ruleset=🤖 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Anthropic/Anthropic.list
ruleset=🤖 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.list
ruleset=🤖 AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=📮 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=📮 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list
ruleset=📮 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleDrive/GoogleDrive.list
ruleset=📮 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleEarth/GoogleEarth.list
ruleset=📮 Google,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=📮 Google,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
ruleset=⏬ 下载规则,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
ruleset=✨️ Samsung,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Samsung/Samsung.list
ruleset=Dell Ltd,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Dell/Dell.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Huawei/Huawei.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cloudflarecn/Cloudflarecn.list
ruleset=☁️ Cloudflare_out,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cloudflare/Cloudflare.list
ruleset=📡 SpeedTest,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list
ruleset=📦 GitHub仓库,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=🐳 DockerHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Docker/Docker.list
ruleset=📧 WhatsApp,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Whatsapp/Whatsapp.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=💽 ApkPure,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apkpure/Apkpure.list
ruleset=🦖 Atlassian,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Atlassian/Atlassian.list
ruleset=🎵 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=📹 Youtube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=🐭 Disney+,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list
ruleset=🌕 全球国际_GFW,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.list
ruleset=📑 学术论文,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Scholar/Scholar.list

ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
;proxy ---------- nodes ---------- group
custom_proxy_group=🚀 手动切换`select`^(?!.*(仅海外用户))(?=.*(港|HK|hk|Hong Kong|HongKong|hongkong|台|新北|彰化|TW|Taiwan|新加坡|坡|狮城|SG|Singapore|英国|英|uk|UK|GB|GBR|London|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|KR|Korea|KOR|首尔|韩|韓|澳大利亚|德国|巴西|土耳其|阿根廷|印度|马来西亚|泰国|越南|乌克兰)).*
custom_proxy_group=🇭🇰 香港节点`url-test`^(?!.*(仅海外用户))(?=.*(港|HK|hk|Hong Kong|HongKong|hongkong)).*`http://www.gstatic.com/generate_204`30,,30
custom_proxy_group=🇨🇳 台湾节点`url-test`^(?!.*(仅海外用户))(?=.*(台|新北|彰化|TW|Taiwan)).*`http://www.gstatic.com/generate_204`30,,30
custom_proxy_group=🇸🇬 新加坡节点`url-test`^(?!.*(仅海外用户))(?=.*(新加坡|坡|狮城|SG|Singapore)).*`http://www.gstatic.com/generate_204`30,,30
custom_proxy_group=🇬🇧 英国节点`url-test`^(?!.*(仅海外用户))(?=.*(英国|英|uk|UK|GB|GBR|London)).*`http://www.gstatic.com/generate_204`30,,30
custom_proxy_group=🇺🇲 美国节点`url-test`^(?!.*(仅海外用户))(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)).*`http://www.gstatic.com/generate_204`30,,30
custom_proxy_group=🇯🇵 日本节点`url-test`^(?!.*(仅海外用户))(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)).*`http://www.gstatic.com/generate_204`30,,30
custom_proxy_group=🇰🇷 韩国节点`url-test`^(?!.*(仅海外用户))(?=.*(KR|Korea|KOR|首尔|韩|韓)).*`http://www.gstatic.com/generate_204`30,,30
custom_proxy_group=🇦🇺 澳大利亚节点`url-test`^(?!.*(仅海外用户))(?=.*(澳大利亚|澳洲)).*`http://www.gstatic.com/generate_204`30,,30
custom_proxy_group=🇩🇪 德国节点`url-test`^(?!.*(仅海外用户))(?=.*(德国|德意志)).*`http://www.gstatic.com/generate_204`30,,30
custom_proxy_group=🔮🇭🇰 香港-负载均衡`load-balance`^(?!.*(仅海外用户))(?=.*(港|HK|hk|Hong Kong|HongKong|hongkong)).*`http://www.gstatic.com/generate_204`30,3000,0
custom_proxy_group=🔮🇸🇬 新加坡-负载均衡`load-balance`^(?!.*(仅海外用户))(?=.*(新加坡|坡|狮城|SG|Singapore)).*`http://www.gstatic.com/generate_204`30,3000,0
custom_proxy_group=🔮🇺🇸 美国-负载均衡`load-balance`^(?!.*(仅海外用户))(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)).*`http://www.gstatic.com/generate_204`30,3000,0
custom_proxy_group=🚀 节点选择`select`[]🔮🇭🇰 香港-负载均衡`[]🔮🇸🇬 新加坡-负载均衡`[]🔮🇺🇸 美国-负载均衡`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇰🇷 韩国节点`[]🇦🇺 澳大利亚节点`[]🇩🇪 德国节点`[]🚀 手动切换`[]DIRECT
;proxy ---------- nodes ---------- group

;proxies ------------------------- group
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🤖 AI`select`[]🚀 节点选择`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📮 Google`select`[]🚀 节点选择`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=Ⓜ️ Microsoft`select`[]🚀 节点选择`[]DIRECT`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=⏬ 下载规则`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=✨️ Samsung`select`[]🚀 节点选择`[]DIRECT`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=Dell Ltd`select`[]🚀 节点选择`[]DIRECT`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🚀 手动切换
custom_proxy_group=☁️ Cloudflare_out`select`[]🚀 节点选择`[]DIRECT`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=📡 SpeedTest`select`[]🚀 节点选择`[]🔮🇭🇰 香港-负载均衡`[]🔮🇸🇬 新加坡-负载均衡`[]🔮🇺🇸 美国-负载均衡`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📦 GitHub仓库`select`[]🚀 节点选择`[]🔮🇭🇰 香港-负载均衡`[]🔮🇸🇬 新加坡-负载均衡`[]🔮🇺🇸 美国-负载均衡`[]DIRECT`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🐳 DockerHub`select`[]🚀 节点选择`[]🔮🇭🇰 香港-负载均衡`[]🔮🇸🇬 新加坡-负载均衡`[]🔮🇺🇸 美国-负载均衡`[]DIRECT`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=📧 WhatsApp`select`[]🚀 节点选择`[]DIRECT`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=📲 Telegram`select`[]🚀 节点选择`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=💽 ApkPure`select`[]🚀 节点选择`[]🔮🇭🇰 香港-负载均衡`[]🔮🇸🇬 新加坡-负载均衡`[]🔮🇺🇸 美国-负载均衡`[]DIRECT`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🦖 Atlassian`select`[]🚀 节点选择`[]DIRECT`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🎵 TikTok`select`[]🇺🇲 美国节点`[]🚀 节点选择`[]DIRECT`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇬🇧 英国节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=📹 Youtube`select`[]🚀 节点选择`[]🔮🇭🇰 香港-负载均衡`[]🔮🇸🇬 新加坡-负载均衡`[]🔮🇺🇸 美国-负载均衡`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🎥 Netflix`select`[]🇸🇬 新加坡节点`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🐭 Disney+`select`[]🇺🇲 美国节点`[]🚀 节点选择`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇬🇧 英国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📺 巴哈姆特`select`[]🇨🇳 台湾节点`[]🔮🇭🇰 香港-负载均衡`[]🔮🇸🇬 新加坡-负载均衡`[]🔮🇺🇸 美国-负载均衡`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🚀 节点选择`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🎮 游戏平台`select`[]🚀 节点选择`[]DIRECT`[]🔮🇭🇰 香港-负载均衡`[]🔮🇸🇬 新加坡-负载均衡`[]🔮🇺🇸 美国-负载均衡`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🌕 全球国际_GFW`select`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📑 学术论文`select`[]🇺🇲 美国节点`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇬🇧 英国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]🚀 节点选择`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🇭🇰 香港节点`[]🚀 节点选择`[]🔮🇭🇰 香港-负载均衡`[]🔮🇸🇬 新加坡-负载均衡`[]🔮🇺🇸 美国-负载均衡`[]DIRECT`[]🇨🇳 台湾节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 英国节点`[]🇰🇷 韩国节点`[]🚀 手动切换
;proxies ------------------------- group

;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
